language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t test_container  -f Dockerfile.dev .

script:
  - docker run -e CI=true test_container npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: docker-react
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-2-940584446841"
  bucket_path: "docker-react"
  on:
    branch: master
